### PR TITLE
add Semiring and Ring instances for Perm

### PR DESCRIPTION
**Pull request by michaelficarra**
Untested, since I don't see any tests. :sweat_smile:

### CODE REVIEW

**Comment by hdgarrood** [comment]
This is very pleasing. :)

Fair enough re tests. I think it should be ok to wait until psc 0.7 and then use https://github.com/purescript/purescript-quickcheck-laws.

Do you think it would make sense to remove the `Semigroup` instance, and get people to use `(+)` where they would currently use `(<>)`? eg `mkPerms (read + write) read read`. Then people could use `Data.Monoid.Additive` or `Data.Monoid.Multiplicative` if they want to use `Perm` with something like `foldMap`.

**Comment by hdgarrood** [comment]
Also, I'm not sure the `Ring` instance is valid. Considering a `Boolean Ring` instance with `(-)` as implication, I think we need `negate a` to be the additive inverse of `a` for all `a`, that is, `a + (negate a) == zero`. However:

```
true + (negate true)
= true + (zero - true)
= true + (zero && not true)
= true + (false && not true)
= true + false
= true || false
= true
/= zero
```

**Comment by hdgarrood** [comment]
I think a `Ring` instance for `Boolean` is impossible - we would need `(zero - a) + a = zero` for all `a`. If we take `true` as `a`, we then need `(false - true) + true = false`. Then, it doesn't matter how we define `(-)`, because (following from the properties of boolean or) `b + true = true` holds for all `b`.

**Comment by michaelficarra** [comment]
I removed the Ring instance.

**Comment by hdgarrood** [comment]
How do you feel about removing the Semigroup instance?

**Pull request merged**
